name: Deploy Hexo site to Pages

on:
  push:
    branches:
      - main   # 你写博客的分支（源码分支）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'v24.5.0'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npx hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./public